from typing import Dict, List, Tuple, Optional

from pydantic import BaseModel, Field


# ==========================================
# 2. OUTGOING RESPONSE SCHEMAS (API -> Client)
# ==========================================

class TheoryPayload(BaseModel):
    """
    Structure for educational theoretical content generated by the AI agent.
    """
    title: str = Field(..., description="Name of the Physical Phenomenon")
    core_concept: str = Field(..., description="Universal explanation of active physics principles")
    governing_equations: List[str] = Field(..., description="LaTeX formatted primary equations")
    real_world_application: str = Field(..., description="Scenario behavior in engineering/aerospace")


class BlueprintItem(BaseModel):
    shape: str = Field(..., description="Shape type for the visual module part")
    scale: List[float] = Field(..., description="X/Y/Z scale or radius values for the shape")
    position: List[float] = Field(..., description="X/Y/Z position offset for the shape")
    color: str = Field(..., description="Hex color string for the shape")


class SimulationResponse(BaseModel):
    """
    Enforces structure on computed 4D data sent out to the Three.js viewport canvas.
    """
    success: bool = Field(..., description="True if the numerical solver executed successfully")
    physics_passed: bool = Field(..., description="True if the vehicle stayed within safe limits")
    message: str = Field(..., description="Status breakdown message detailing flight success or crash events")
    theory: Optional[TheoryPayload] = Field(None, description="The educational physics lesson payload")
    model_type: str = Field(..., description="The calculated category mode: 'rocket', 'orbital', etc.")
    labels: List[str] = Field(..., description="The context labels for each column axis index in the y matrix")
    t: List[float] = Field(..., description="The 4th dimension: full array timeline steps")
    y: List[List[float]] = Field(..., description="The multi-dimensional coordinate trajectory states per step")
    parameters: Dict[str, float] = Field(..., description="The engineering configuration constants generated")
    blueprint: Optional[List[BlueprintItem]] = Field(None, description="Optional generated visual module blueprint")
    prompt: str = Field(..., description="Echoes back the starting user parameter string")


class ConfigResponse(BaseModel):
    """
    Validates raw config parameters when reviewing state data prior to trajectory steps.
    """
    model_type: str
    prompt: str
    state_labels: List[str]
    initial_state: List[float]
    time_span: Tuple[float, float]
    time_steps: List[float]
    parameters: Dict[str, float]
    blueprint: Optional[List[BlueprintItem]] = Field(None, description="Optional generated visual module blueprint")
    control_inputs: Dict[str, List[float]]
